auto_sync = true
enter_accept = false
search_mode = "fuzzy"
sync_address = "https://atuin.codewalker.dev"
filter_mode = "global"

[daemon]
enabled = true
autostart = true

[theme]
name = "catppuccin-macchiato-teal"

[search]
shells = "all"
